name: 'Discord Alarm'

on: schedule:
  - cron: '37 * * * *'

jobs:
  webhook:
    name: 'WEBHOOK'

    runs-on: 'ubuntu-latest'

    - name: Send a message to Discord
      shell: bash
      run: |
       curl -X POST https://discord.com/api/webhooks/1113745307314958367/RrSby1al_BTdeupYcC3TQj1mnTjvyMTLFnudRIjeyN45CBIMefr_3Fn_gJOHg2wuX4XH \
       -H 'Content-type: multipart/form-data' \
       -d '{
          "content": "테스트"
        }'